### ISSUE TITLE
Searching and selecting a Chrome tab goes to the tab right before it...

### ISSUE THREAD

**Issue by dstj** [christianrondeau/GoToWindow#34]
Using v0.2.0, when searching and selecting a Chrome tab from the GotoWindow search and drop down boxes, the Chrome tab immediately before the one I searched for gets opened...

So, in other words, I have tabs X, Y, Z. I search for Y, but X gets opened...

**Comment by christianrondeau** [comment]
Can you still reproduce in the latest version^

**Comment by christianrondeau** [comment]
Closing. Please re-open if you have the issue again.
