### ISSUE TITLE
Unable to customize shortcut as ctrl + '

### ISSUE THREAD

**Issue by amosbird** [christianrondeau/GoToWindow#38]
Is there some constrains for not allowing customizing hotkeys?

**Comment by christianrondeau** [comment]
Not really, other than time. The last release finally allows other shortcuts than <kbd>alt</kbd> <kbd>tab</kbd>, so it's only a matter of adding a UI to select your desired shortcut :)

I'll look into this, thanks for the feedback!

**Comment by amosbird** [comment]
Thanks for this amazing tool.

**Comment by christianrondeau** [comment]
It should now work in 0.4.0 :) Let me know if it works for you!

**Comment by amosbird** [comment]
Great. It seems no problem for me.
