### ISSUE TITLE
One tabkey stroke to start selecting

### ISSUE THREAD

**Issue by amosbird** [christianrondeau/GoToWindow#39]
Currently when I type the window name in GoToWindow panel, I need to hit Tab twice to start selecting items, or press ctrl+num. It will be more ergonomic to type Tab only once.

**Comment by christianrondeau** [comment]
Probably some leftovers from changing the shortcut and still expecting the first <kbd>Tab</kbd> to be the "up" state from the <kbd>Alt</kbd> + <kbd>Tab</kbd> keystroke. Should be simple to fix, thanks for raising it!

**Comment by christianrondeau** [comment]
The first tab highlighted the `x` button. I just skipped this button when using <kbd>Tab</kbd> since you can use <kbd>Esc</kbd> anyway.

Note that you can just type your window name, and press up/down too. The next update will solve your specific use case.

**Comment by christianrondeau** [comment]
:)
