### ISSUE TITLE
Empty directories created when started

### ISSUE THREAD

**Issue by jeffrimko** [christianrondeau/GoToWindow#40]
Running the portable zip file version of `0.4.1` (saw same issue with `0.3.0` also). When started, it creates the empty directories `GoToWindow` and `GoToWindow\packages` two directories above the installed directory. For example, if the zip file is extracted to `C:\DirA\DirB\GoToWindow`, it will create `C:\DirA\GoToWindow` and `C:\DirA\GoToWindow\packages` upon start.

**Comment by christianrondeau** [comment]
Mmmh, I guess that's [Squirrel](https://github.com/Squirrel/Squirrel.Windows) or my own implementation based on where it "should" be installed that's not taking the portable version. Thanks for raising it, I'll look into it!

**Comment by jeffrimko** [comment]
Tried debugging it further but I'm not very familiar with the MS toolchain. It seems like it is due to Squirrel although I cannot tell exactly the create directory calls happens; stepping through the GTW code shows the call stack is at `Splat.dll!Splat.LogHost.Log<Squirrel.UpdateManager.CheckForUpdateImpl>(Squirrel.UpdateManager.CheckForUpdateImpl This)` but I am not set up to step through the third-party code. It looks like a there may be an exception thrown where `GoToWindow\packages\RELEASES` cannot be found which leads to the directories being created.

**Comment by christianrondeau** [comment]
I didn't have time to look into it yet, but what you say makes sense; in that case, I simply have to skip all Squirrel (`UpdateManager`) code if the app was not installed through Squirrel, e.g. by looking up if the app is running under the `AppData` folder. Thanks for taking the time!

**Comment by christianrondeau** [comment]
Found the issue, it's indeed in Squirrel. I created an issue (see https://github.com/Squirrel/Squirrel.Windows/issues/455) and I will make a workaround in the meantime.

**Comment by christianrondeau** [comment]
That should work now, can you confirm it works for you?

**Comment by jeffrimko** [comment]
Having some trouble running the new version. I don't have .NET Framework 4.6.1 and MS keeps suggesting that I install 4.6 instead (which is already installed). Running Windows 7 Home Premium 64-bit with SP1.

**Comment by christianrondeau** [comment]
Mmmh, yeah I did update to 4.6.1, I didn't really need to and I can rollback this. I have created a new issue #42.

In the meantime, can you try this? https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by christianrondeau** [comment]
I rolled back to upgrade to 4.6.1 since it wasn't bringing anything new to the table anyway. See v0.5.1.
