### ISSUE TITLE
New feature for quick switch.

### ISSUE THREAD

**Issue by amosbird** [christianrondeau/GoToWindow#41]
I wonder if it's possible to do the followings:
* pressing `hotkey` less than say 200ms acts as AltTab
* pressing `hotkey` longer than 200ms pops up GoToWindow bar

**Comment by christianrondeau** [comment]
Hi @amosbird - thanks for the suggestion, I have less time these days to spend on GoToWindow, but I'll look into it :)

**Comment by christianrondeau** [comment]
Sorry it wasn't done; moving and having a baby both slowed down my pace :)
