### ISSUE TITLE
Firefox 55 (beta): all open tabs are displayed as windows

### ISSUE THREAD

**Issue by bybor** [christianrondeau/GoToWindow#52]
I checked it's not a new Firefox feature, Windows Alt-Tab shows only Firefox process, nothing else

**Comment by christianrondeau** [comment]
Interesting. Maybe they changed the window structure? All the code is here, if you're willing to take a look: https://github.com/christianrondeau/GoToWindow/blob/master/GoToWindow.Plugins.ExpandBrowsersTabs/Firefox/FirefoxTabsFinder.cs

You'll also need a tool to inspect the Firefox UI structure (it was UISpy, but it's obsolete, I don't remember the newer one)

**Comment by bybor** [comment]
AFAICS, what I thought of being an issue, is actually a plugin enabled behavior. After I removed the plugin's dll I got a single line for Firefox in the list of processes, just what suits my workflow. Thank you!

**Comment by christianrondeau** [comment]
Weird, so there's probably still a bug, but I'm glad to hear it's not blocking you anymore!
